### ISSUE TITLE
Log when updated image found

### ISSUE THREAD

**Issue by swat30** [CloudBrewery/docrane#12]
Log when an updated image is found for a container before restarting.

**Comment by thurloat** [comment]
not sure I follow this, do you mean that we should log when a newer image enters the images list?

**Comment by swat30** [comment]
@thurloat https://github.com/CloudBrewery/docrane/commit/70d1705fdb35467849cd86e1b18f271d1d08c4e4 :)

**Comment by thurloat** [comment]
got it. :+1:
